/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomFieldOption'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomFieldOption'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.CustomFieldMetaData = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.CustomFieldOption);
  }
}(this, function(ApiClient, CustomFieldOption) {
  'use strict';

  /**
   * The CustomFieldMetaData model module.
   * @module model/CustomFieldMetaData
   * @version V1.0
   */

  /**
   * Constructs a new <code>CustomFieldMetaData</code>.
   * @alias module:model/CustomFieldMetaData
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>CustomFieldMetaData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomFieldMetaData} obj Optional instance to populate.
   * @return {module:model/CustomFieldMetaData} The populated <code>CustomFieldMetaData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('field_type'))
        obj.fieldType = ApiClient.convertToType(data['field_type'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('options'))
        obj.options = ApiClient.convertToType(data['options'], [CustomFieldOption]);
    }
    return obj;
  }

  /**
   * @member {module:model/CustomFieldMetaData.FieldTypeEnum} fieldType
   */
  exports.prototype.fieldType = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} label
   */
  exports.prototype.label = undefined;

  /**
   * @member {Array.<module:model/CustomFieldOption>} options
   */
  exports.prototype.options = undefined;


  /**
   * Allowed values for the <code>fieldType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.FieldTypeEnum = {
    /**
     * value: "Currency"
     * @const
     */
    currency: "Currency",

    /**
     * value: "Date"
     * @const
     */
    _date: "Date",

    /**
     * value: "DateTime"
     * @const
     */
    dateTime: "DateTime",

    /**
     * value: "DayOfWeek"
     * @const
     */
    dayOfWeek: "DayOfWeek",

    /**
     * value: "Drilldown"
     * @const
     */
    drilldown: "Drilldown",

    /**
     * value: "Email"
     * @const
     */
    email: "Email",

    /**
     * value: "Month"
     * @const
     */
    month: "Month",

    /**
     * value: "ListBox"
     * @const
     */
    listBox: "ListBox",

    /**
     * value: "Name"
     * @const
     */
    name: "Name",

    /**
     * value: "WholeNumber"
     * @const
     */
    wholeNumber: "WholeNumber",

    /**
     * value: "DecimalNumber"
     * @const
     */
    decimalNumber: "DecimalNumber",

    /**
     * value: "Percent"
     * @const
     */
    percent: "Percent",

    /**
     * value: "PhoneNumber"
     * @const
     */
    phoneNumber: "PhoneNumber",

    /**
     * value: "Radio"
     * @const
     */
    radio: "Radio",

    /**
     * value: "Dropdown"
     * @const
     */
    dropdown: "Dropdown",

    /**
     * value: "SocialSecurityNumber"
     * @const
     */
    socialSecurityNumber: "SocialSecurityNumber",

    /**
     * value: "State"
     * @const
     */
    state: "State",

    /**
     * value: "Text"
     * @const
     */
    text: "Text",

    /**
     * value: "TextArea"
     * @const
     */
    textArea: "TextArea",

    /**
     * value: "User"
     * @const
     */
    user: "User",

    /**
     * value: "UserListBox"
     * @const
     */
    userListBox: "UserListBox",

    /**
     * value: "Website"
     * @const
     */
    website: "Website",

    /**
     * value: "Year"
     * @const
     */
    year: "Year",

    /**
     * value: "YesNo"
     * @const
     */
    yesNo: "YesNo"
  };

  return exports;

}));
