/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.EntryLongString = factory(root.InfusionsoftRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The EntryLongString model module.
   * @module model/EntryLongString
   * @version V1.0
   */

  /**
   * Constructs a new <code>EntryLongString</code>.
   * @alias module:model/EntryLongString
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>EntryLongString</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntryLongString} obj Optional instance to populate.
   * @return {module:model/EntryLongString} The populated <code>EntryLongString</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('key'))
        obj.key = ApiClient.convertToType(data['key'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/EntryLongString.KeyEnum} key
   */
  exports.prototype.key = undefined;


  /**
   * Allowed values for the <code>key</code> property.
   * @enum {String}
   * @readonly
   */
  exports.KeyEnum = {
    /**
     * value: "SUCCESS"
     * @const
     */
    SUCCESS: "SUCCESS",

    /**
     * value: "DUPLICATE"
     * @const
     */
    DUPLICATE: "DUPLICATE",

    /**
     * value: "CONTACT_NOT_FOUND"
     * @const
     */
    CONTACT_NOT_FOUND: "CONTACT_NOT_FOUND",

    /**
     * value: "TAG_ID_NOT_FOUND"
     * @const
     */
    TAG_ID_NOT_FOUND: "TAG_ID_NOT_FOUND",

    /**
     * value: "FAILURE"
     * @const
     */
    FAILURE: "FAILURE"
  };

  return exports;

}));
