/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HistoricalCounts'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HistoricalCounts'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Goal = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.HistoricalCounts);
  }
}(this, function(ApiClient, HistoricalCounts) {
  'use strict';

  /**
   * The Goal model module.
   * @module model/Goal
   * @version V1.0
   */

  /**
   * Constructs a new <code>Goal</code>.
   * @alias module:model/Goal
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Goal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Goal} obj Optional instance to populate.
   * @return {module:model/Goal} The populated <code>Goal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('historical_contact_counts'))
        obj.historicalContactCounts = HistoricalCounts.constructFromObject(data['historical_contact_counts']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('next_sequence_ids'))
        obj.nextSequenceIds = ApiClient.convertToType(data['next_sequence_ids'], ['Number']);
      if (data.hasOwnProperty('previous_sequence_ids'))
        obj.previousSequenceIds = ApiClient.convertToType(data['previous_sequence_ids'], ['Number']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * @member {module:model/HistoricalCounts} historicalContactCounts
   */
  exports.prototype.historicalContactCounts = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Array.<Number>} nextSequenceIds
   */
  exports.prototype.nextSequenceIds = undefined;

  /**
   * @member {Array.<Number>} previousSequenceIds
   */
  exports.prototype.previousSequenceIds = undefined;

  /**
   * @member {module:model/Goal.TypeEnum} type
   */
  exports.prototype.type = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "WebForm"
     * @const
     */
    webForm: "WebForm",

    /**
     * value: "LandingPage"
     * @const
     */
    landingPage: "LandingPage",

    /**
     * value: "Survey"
     * @const
     */
    survey: "Survey",

    /**
     * value: "LinkClick"
     * @const
     */
    linkClick: "LinkClick",

    /**
     * value: "Score"
     * @const
     */
    score: "Score",

    /**
     * value: "Purchase"
     * @const
     */
    purchase: "Purchase",

    /**
     * value: "Quote"
     * @const
     */
    quote: "Quote",

    /**
     * value: "WebsiteTrigger"
     * @const
     */
    websiteTrigger: "WebsiteTrigger",

    /**
     * value: "InternalForm"
     * @const
     */
    internalForm: "InternalForm",

    /**
     * value: "Task"
     * @const
     */
    task: "Task",

    /**
     * value: "StageMove"
     * @const
     */
    stageMove: "StageMove",

    /**
     * value: "Note"
     * @const
     */
    note: "Note",

    /**
     * value: "Tag"
     * @const
     */
    tag: "Tag",

    /**
     * value: "GroSocial"
     * @const
     */
    groSocial: "GroSocial",

    /**
     * value: "TwitterForm"
     * @const
     */
    twitterForm: "TwitterForm",

    /**
     * value: "API"
     * @const
     */
    API: "API",

    /**
     * value: "WordPress"
     * @const
     */
    wordPress: "WordPress",

    /**
     * value: "NewLandingPage"
     * @const
     */
    newLandingPage: "NewLandingPage"
  };

  return exports;

}));
