/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.HistoricalCounts = factory(root.InfusionsoftRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The HistoricalCounts model module.
   * @module model/HistoricalCounts
   * @version V1.0
   */

  /**
   * Constructs a new <code>HistoricalCounts</code>.
   * @alias module:model/HistoricalCounts
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>HistoricalCounts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/HistoricalCounts} obj Optional instance to populate.
   * @return {module:model/HistoricalCounts} The populated <code>HistoricalCounts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('24_hours'))
        obj._24Hours = ApiClient.convertToType(data['24_hours'], 'Number');
      if (data.hasOwnProperty('30_days'))
        obj._30Days = ApiClient.convertToType(data['30_days'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} _24Hours
   */
  exports.prototype._24Hours = undefined;

  /**
   * @member {Number} _30Days
   */
  exports.prototype._30Days = undefined;

  return exports;

}));
