/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OrderContactDetails', 'model/OrderItem', 'model/ShippingInformation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OrderContactDetails'), require('./OrderItem'), require('./ShippingInformation'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Order = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.OrderContactDetails, root.InfusionsoftRestApi.OrderItem, root.InfusionsoftRestApi.ShippingInformation);
  }
}(this, function(ApiClient, OrderContactDetails, OrderItem, ShippingInformation) {
  'use strict';

  /**
   * The Order model module.
   * @module model/Order
   * @version V1.0
   */

  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('contact'))
        obj.contact = OrderContactDetails.constructFromObject(data['contact']);
      if (data.hasOwnProperty('creation_date'))
        obj.creationDate = ApiClient.convertToType(data['creation_date'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('lead_affiliate_id'))
        obj.leadAffiliateId = ApiClient.convertToType(data['lead_affiliate_id'], 'Number');
      if (data.hasOwnProperty('modification_date'))
        obj.modificationDate = ApiClient.convertToType(data['modification_date'], 'String');
      if (data.hasOwnProperty('order_date'))
        obj.orderDate = ApiClient.convertToType(data['order_date'], 'String');
      if (data.hasOwnProperty('order_items'))
        obj.orderItems = ApiClient.convertToType(data['order_items'], [OrderItem]);
      if (data.hasOwnProperty('recurring'))
        obj.recurring = ApiClient.convertToType(data['recurring'], 'Boolean');
      if (data.hasOwnProperty('refund_total'))
        obj.refundTotal = ApiClient.convertToType(data['refund_total'], 'Number');
      if (data.hasOwnProperty('sales_affiliate_id'))
        obj.salesAffiliateId = ApiClient.convertToType(data['sales_affiliate_id'], 'Number');
      if (data.hasOwnProperty('shipping_information'))
        obj.shippingInformation = ShippingInformation.constructFromObject(data['shipping_information']);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('total'))
        obj.total = ApiClient.convertToType(data['total'], 'Number');
      if (data.hasOwnProperty('total_due'))
        obj.totalDue = ApiClient.convertToType(data['total_due'], 'Number');
      if (data.hasOwnProperty('total_paid'))
        obj.totalPaid = ApiClient.convertToType(data['total_paid'], 'Number');
    }
    return obj;
  }

  /**
   * @member {module:model/OrderContactDetails} contact
   */
  exports.prototype.contact = undefined;

  /**
   * @member {String} creationDate
   */
  exports.prototype.creationDate = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} leadAffiliateId
   */
  exports.prototype.leadAffiliateId = undefined;

  /**
   * @member {String} modificationDate
   */
  exports.prototype.modificationDate = undefined;

  /**
   * @member {String} orderDate
   */
  exports.prototype.orderDate = undefined;

  /**
   * @member {Array.<module:model/OrderItem>} orderItems
   */
  exports.prototype.orderItems = undefined;

  /**
   * @member {Boolean} recurring
   */
  exports.prototype.recurring = undefined;

  /**
   * @member {Number} refundTotal
   */
  exports.prototype.refundTotal = undefined;

  /**
   * @member {Number} salesAffiliateId
   */
  exports.prototype.salesAffiliateId = undefined;

  /**
   * @member {module:model/ShippingInformation} shippingInformation
   */
  exports.prototype.shippingInformation = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {Number} total
   */
  exports.prototype.total = undefined;

  /**
   * @member {Number} totalDue
   */
  exports.prototype.totalDue = undefined;

  /**
   * @member {Number} totalPaid
   */
  exports.prototype.totalPaid = undefined;

  return exports;

}));
