/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Relationship = factory(root.InfusionsoftRestApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Relationship model module.
   * @module model/Relationship
   * @version V1.0
   */

  /**
   * Constructs a new <code>Relationship</code>.
   * @alias module:model/Relationship
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Relationship</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Relationship} obj Optional instance to populate.
   * @return {module:model/Relationship} The populated <code>Relationship</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('linked_contact_id'))
        obj.linkedContactId = ApiClient.convertToType(data['linked_contact_id'], 'Number');
      if (data.hasOwnProperty('relationship_type_id'))
        obj.relationshipTypeId = ApiClient.convertToType(data['relationship_type_id'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Number} linkedContactId
   */
  exports.prototype.linkedContactId = undefined;

  /**
   * @member {Number} relationshipTypeId
   */
  exports.prototype.relationshipTypeId = undefined;

  return exports;

}));
