/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HistoricalCounts', 'model/SequencePath'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HistoricalCounts'), require('./SequencePath'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Sequence = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.HistoricalCounts, root.InfusionsoftRestApi.SequencePath);
  }
}(this, function(ApiClient, HistoricalCounts, SequencePath) {
  'use strict';

  /**
   * The Sequence model module.
   * @module model/Sequence
   * @version V1.0
   */

  /**
   * Constructs a new <code>Sequence</code>.
   * @alias module:model/Sequence
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Sequence</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Sequence} obj Optional instance to populate.
   * @return {module:model/Sequence} The populated <code>Sequence</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('active_contact_count'))
        obj.activeContactCount = ApiClient.convertToType(data['active_contact_count'], 'Number');
      if (data.hasOwnProperty('active_contact_count_completed'))
        obj.activeContactCountCompleted = ApiClient.convertToType(data['active_contact_count_completed'], 'Number');
      if (data.hasOwnProperty('historical_contact_count'))
        obj.historicalContactCount = HistoricalCounts.constructFromObject(data['historical_contact_count']);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('paths'))
        obj.paths = ApiClient.convertToType(data['paths'], [SequencePath]);
    }
    return obj;
  }

  /**
   * @member {Number} activeContactCount
   */
  exports.prototype.activeContactCount = undefined;

  /**
   * @member {Number} activeContactCountCompleted
   */
  exports.prototype.activeContactCountCompleted = undefined;

  /**
   * @member {module:model/HistoricalCounts} historicalContactCount
   */
  exports.prototype.historicalContactCount = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Array.<module:model/SequencePath>} paths
   */
  exports.prototype.paths = undefined;

  return exports;

}));
