/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CheckListItemDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CheckListItemDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.StageDetails = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.CheckListItemDetails);
  }
}(this, function(ApiClient, CheckListItemDetails) {
  'use strict';

  /**
   * The StageDetails model module.
   * @module model/StageDetails
   * @version V1.0
   */

  /**
   * Constructs a new <code>StageDetails</code>.
   * @alias module:model/StageDetails
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>StageDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StageDetails} obj Optional instance to populate.
   * @return {module:model/StageDetails} The populated <code>StageDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('check_list_items'))
        obj.checkListItems = ApiClient.convertToType(data['check_list_items'], [CheckListItemDetails]);
      if (data.hasOwnProperty('probability'))
        obj.probability = ApiClient.convertToType(data['probability'], 'Number');
      if (data.hasOwnProperty('stage_order'))
        obj.stageOrder = ApiClient.convertToType(data['stage_order'], 'Number');
      if (data.hasOwnProperty('target_num_days'))
        obj.targetNumDays = ApiClient.convertToType(data['target_num_days'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CheckListItemDetails>} checkListItems
   */
  exports.prototype.checkListItems = undefined;

  /**
   * @member {Number} probability
   */
  exports.prototype.probability = undefined;

  /**
   * @member {Number} stageOrder
   */
  exports.prototype.stageOrder = undefined;

  /**
   * @member {Number} targetNumDays
   */
  exports.prototype.targetNumDays = undefined;

  return exports;

}));
