/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BasicContact'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BasicContact'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Task = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.BasicContact);
  }
}(this, function(ApiClient, BasicContact) {
  'use strict';

  /**
   * The Task model module.
   * @module model/Task
   * @version V1.0
   */

  /**
   * Constructs a new <code>Task</code>.
   * @alias module:model/Task
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Task</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Task} obj Optional instance to populate.
   * @return {module:model/Task} The populated <code>Task</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('completed'))
        obj.completed = ApiClient.convertToType(data['completed'], 'Boolean');
      if (data.hasOwnProperty('completion_date'))
        obj.completionDate = ApiClient.convertToType(data['completion_date'], 'String');
      if (data.hasOwnProperty('contact'))
        obj.contact = BasicContact.constructFromObject(data['contact']);
      if (data.hasOwnProperty('creation_date'))
        obj.creationDate = ApiClient.convertToType(data['creation_date'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('due_date'))
        obj.dueDate = ApiClient.convertToType(data['due_date'], 'String');
      if (data.hasOwnProperty('modification_date'))
        obj.modificationDate = ApiClient.convertToType(data['modification_date'], 'String');
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'Number');
    }
    return obj;
  }

  /**
   * @member {Boolean} completed
   */
  exports.prototype.completed = undefined;

  /**
   * @member {String} completionDate
   */
  exports.prototype.completionDate = undefined;

  /**
   * @member {module:model/BasicContact} contact
   */
  exports.prototype.contact = undefined;

  /**
   * @member {String} creationDate
   */
  exports.prototype.creationDate = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} dueDate
   */
  exports.prototype.dueDate = undefined;

  /**
   * @member {String} modificationDate
   */
  exports.prototype.modificationDate = undefined;

  /**
   * @member {Number} priority
   */
  exports.prototype.priority = undefined;

  /**
   * @member {String} title
   */
  exports.prototype.title = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * @member {Number} userId
   */
  exports.prototype.userId = undefined;

  return exports;

}));
