/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Order'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Order'));
  } else {
    // Browser globals (root is window)
    if (!root.InfusionsoftRestApi) {
      root.InfusionsoftRestApi = {};
    }
    root.InfusionsoftRestApi.Transaction = factory(root.InfusionsoftRestApi.ApiClient, root.InfusionsoftRestApi.Order);
  }
}(this, function(ApiClient, Order) {
  'use strict';

  /**
   * The Transaction model module.
   * @module model/Transaction
   * @version V1.0
   */

  /**
   * Constructs a new <code>Transaction</code>.
   * @alias module:model/Transaction
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transaction} obj Optional instance to populate.
   * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('collection_method'))
        obj.collectionMethod = ApiClient.convertToType(data['collection_method'], 'String');
      if (data.hasOwnProperty('contact_id'))
        obj.contactId = ApiClient.convertToType(data['contact_id'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('errors'))
        obj.errors = ApiClient.convertToType(data['errors'], 'String');
      if (data.hasOwnProperty('gateway'))
        obj.gateway = ApiClient.convertToType(data['gateway'], 'String');
      if (data.hasOwnProperty('gateway_account_name'))
        obj.gatewayAccountName = ApiClient.convertToType(data['gateway_account_name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('order_ids'))
        obj.orderIds = ApiClient.convertToType(data['order_ids'], 'String');
      if (data.hasOwnProperty('orders'))
        obj.orders = ApiClient.convertToType(data['orders'], [Order]);
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('test'))
        obj.test = ApiClient.convertToType(data['test'], 'Boolean');
      if (data.hasOwnProperty('transaction_date'))
        obj.transactionDate = ApiClient.convertToType(data['transaction_date'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} amount
   */
  exports.prototype.amount = undefined;

  /**
   * @member {String} collectionMethod
   */
  exports.prototype.collectionMethod = undefined;

  /**
   * @member {Number} contactId
   */
  exports.prototype.contactId = undefined;

  /**
   * @member {String} currency
   */
  exports.prototype.currency = undefined;

  /**
   * @member {String} errors
   */
  exports.prototype.errors = undefined;

  /**
   * @member {String} gateway
   */
  exports.prototype.gateway = undefined;

  /**
   * @member {String} gatewayAccountName
   */
  exports.prototype.gatewayAccountName = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} orderIds
   */
  exports.prototype.orderIds = undefined;

  /**
   * @member {Array.<module:model/Order>} orders
   */
  exports.prototype.orders = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Boolean} test
   */
  exports.prototype.test = undefined;

  /**
   * @member {String} transactionDate
   */
  exports.prototype.transactionDate = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  return exports;

}));
