/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Campaign', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.Campaign();
      });

      it('should create an instance of Campaign', function() {
        // TODO: update the code to test Campaign
        expect(instance).to.be.a(InfusionsoftRestApi.Campaign);
      });

      it('should have the property activeContactCount (base name: "active_contact_count")', function() {
        // TODO: update the code to test the property activeContactCount
        expect(instance).to.have.property('activeContactCount');
        // expect(instance.activeContactCount).to.be(expectedValueLiteral);
      });

      it('should have the property completedContactCount (base name: "completed_contact_count")', function() {
        // TODO: update the code to test the property completedContactCount
        expect(instance).to.have.property('completedContactCount');
        // expect(instance.completedContactCount).to.be(expectedValueLiteral);
      });

      it('should have the property dateCreated (base name: "date_created")', function() {
        // TODO: update the code to test the property dateCreated
        expect(instance).to.have.property('dateCreated');
        // expect(instance.dateCreated).to.be(expectedValueLiteral);
      });

      it('should have the property errorMessage (base name: "error_message")', function() {
        // TODO: update the code to test the property errorMessage
        expect(instance).to.have.property('errorMessage');
        // expect(instance.errorMessage).to.be(expectedValueLiteral);
      });

      it('should have the property goals (base name: "goals")', function() {
        // TODO: update the code to test the property goals
        expect(instance).to.have.property('goals');
        // expect(instance.goals).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property publishedDate (base name: "published_date")', function() {
        // TODO: update the code to test the property publishedDate
        expect(instance).to.have.property('publishedDate');
        // expect(instance.publishedDate).to.be(expectedValueLiteral);
      });

      it('should have the property publishedStatus (base name: "published_status")', function() {
        // TODO: update the code to test the property publishedStatus
        expect(instance).to.have.property('publishedStatus');
        // expect(instance.publishedStatus).to.be(expectedValueLiteral);
      });

      it('should have the property publishedTimeZone (base name: "published_time_zone")', function() {
        // TODO: update the code to test the property publishedTimeZone
        expect(instance).to.have.property('publishedTimeZone');
        // expect(instance.publishedTimeZone).to.be(expectedValueLiteral);
      });

      it('should have the property sequences (base name: "sequences")', function() {
        // TODO: update the code to test the property sequences
        expect(instance).to.have.property('sequences');
        // expect(instance.sequences).to.be(expectedValueLiteral);
      });

      it('should have the property timeZone (base name: "time_zone")', function() {
        // TODO: update the code to test the property timeZone
        expect(instance).to.have.property('timeZone');
        // expect(instance.timeZone).to.be(expectedValueLiteral);
      });

    });
  });

}));
