/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CheckListItemDetails', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.CheckListItemDetails();
      });

      it('should create an instance of CheckListItemDetails', function() {
        // TODO: update the code to test CheckListItemDetails
        expect(instance).to.be.a(InfusionsoftRestApi.CheckListItemDetails);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property doneDate (base name: "done_date")', function() {
        // TODO: update the code to test the property doneDate
        expect(instance).to.have.property('doneDate');
        // expect(instance.doneDate).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property instanceId (base name: "instance_id")', function() {
        // TODO: update the code to test the property instanceId
        expect(instance).to.have.property('instanceId');
        // expect(instance.instanceId).to.be(expectedValueLiteral);
      });

      it('should have the property itemOrder (base name: "item_order")', function() {
        // TODO: update the code to test the property itemOrder
        expect(instance).to.have.property('itemOrder');
        // expect(instance.itemOrder).to.be(expectedValueLiteral);
      });

      it('should have the property required (base name: "required")', function() {
        // TODO: update the code to test the property required
        expect(instance).to.have.property('required');
        // expect(instance.required).to.be(expectedValueLiteral);
      });

    });
  });

}));
