/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Goal', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.Goal();
      });

      it('should create an instance of Goal', function() {
        // TODO: update the code to test Goal
        expect(instance).to.be.a(InfusionsoftRestApi.Goal);
      });

      it('should have the property historicalContactCounts (base name: "historical_contact_counts")', function() {
        // TODO: update the code to test the property historicalContactCounts
        expect(instance).to.have.property('historicalContactCounts');
        // expect(instance.historicalContactCounts).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property nextSequenceIds (base name: "next_sequence_ids")', function() {
        // TODO: update the code to test the property nextSequenceIds
        expect(instance).to.have.property('nextSequenceIds');
        // expect(instance.nextSequenceIds).to.be(expectedValueLiteral);
      });

      it('should have the property previousSequenceIds (base name: "previous_sequence_ids")', function() {
        // TODO: update the code to test the property previousSequenceIds
        expect(instance).to.have.property('previousSequenceIds');
        // expect(instance.previousSequenceIds).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
