/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('HistoricalCounts', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.HistoricalCounts();
      });

      it('should create an instance of HistoricalCounts', function() {
        // TODO: update the code to test HistoricalCounts
        expect(instance).to.be.a(InfusionsoftRestApi.HistoricalCounts);
      });

      it('should have the property _24Hours (base name: "24_hours")', function() {
        // TODO: update the code to test the property _24Hours
        expect(instance).to.have.property('_24Hours');
        // expect(instance._24Hours).to.be(expectedValueLiteral);
      });

      it('should have the property _30Days (base name: "30_days")', function() {
        // TODO: update the code to test the property _30Days
        expect(instance).to.have.property('_30Days');
        // expect(instance._30Days).to.be(expectedValueLiteral);
      });

    });
  });

}));
