/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SalesPipeline', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.SalesPipeline();
      });

      it('should create an instance of SalesPipeline', function() {
        // TODO: update the code to test SalesPipeline
        expect(instance).to.be.a(InfusionsoftRestApi.SalesPipeline);
      });

      it('should have the property endStage (base name: "end_stage")', function() {
        // TODO: update the code to test the property endStage
        expect(instance).to.have.property('endStage');
        // expect(instance.endStage).to.be(expectedValueLiteral);
      });

      it('should have the property isDefault (base name: "is_default")', function() {
        // TODO: update the code to test the property isDefault
        expect(instance).to.have.property('isDefault');
        // expect(instance.isDefault).to.be(expectedValueLiteral);
      });

      it('should have the property stageCount (base name: "stage_count")', function() {
        // TODO: update the code to test the property stageCount
        expect(instance).to.have.property('stageCount');
        // expect(instance.stageCount).to.be(expectedValueLiteral);
      });

      it('should have the property stageId (base name: "stage_id")', function() {
        // TODO: update the code to test the property stageId
        expect(instance).to.have.property('stageId');
        // expect(instance.stageId).to.be(expectedValueLiteral);
      });

      it('should have the property stageName (base name: "stage_name")', function() {
        // TODO: update the code to test the property stageName
        expect(instance).to.have.property('stageName');
        // expect(instance.stageName).to.be(expectedValueLiteral);
      });

      it('should have the property stageOrder (base name: "stage_order")', function() {
        // TODO: update the code to test the property stageOrder
        expect(instance).to.have.property('stageOrder');
        // expect(instance.stageOrder).to.be(expectedValueLiteral);
      });

    });
  });

}));
