/*
 * Infusionsoft REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: V1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.InfusionsoftRestApi);
  }
}(this, function(expect, InfusionsoftRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Sequence', function() {
      beforeEach(function() {
        instance = new InfusionsoftRestApi.Sequence();
      });

      it('should create an instance of Sequence', function() {
        // TODO: update the code to test Sequence
        expect(instance).to.be.a(InfusionsoftRestApi.Sequence);
      });

      it('should have the property activeContactCount (base name: "active_contact_count")', function() {
        // TODO: update the code to test the property activeContactCount
        expect(instance).to.have.property('activeContactCount');
        // expect(instance.activeContactCount).to.be(expectedValueLiteral);
      });

      it('should have the property activeContactCountCompleted (base name: "active_contact_count_completed")', function() {
        // TODO: update the code to test the property activeContactCountCompleted
        expect(instance).to.have.property('activeContactCountCompleted');
        // expect(instance.activeContactCountCompleted).to.be(expectedValueLiteral);
      });

      it('should have the property historicalContactCount (base name: "historical_contact_count")', function() {
        // TODO: update the code to test the property historicalContactCount
        expect(instance).to.have.property('historicalContactCount');
        // expect(instance.historicalContactCount).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property paths (base name: "paths")', function() {
        // TODO: update the code to test the property paths
        expect(instance).to.have.property('paths');
        // expect(instance.paths).to.be(expectedValueLiteral);
      });

    });
  });

}));
